[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50
runOnSave = true

[browser]
gatherUsageStats = false

[global]
developmentMode = false

[theme]
primaryColor = "#1abc9c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
